[workspace]
resolver = "3"
members = ["core", "plugins/calc", "util", "widget"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
log = "0.4.26"
bytemuck = "1.21.0"
env_logger = "0.11.7"
hashbrown = "0.15"
lazy_static = "1.5.0"
uuid.version = "1.16.0"
uuid.features = ["v4"]
pollster = "0.4.0"
serde = "1.0"
thiserror = "2.0.12"

## Main package

[package]
name = "depot_tools"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
env_logger.workspace = true
depot_core.path = "core"
widget.path = "widget"

[dev-dependencies]
ratatui = "0.29.0"
