[workspace]
resolver = "3"
members = ["core", "widget"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.100"
bytemuck = "1.21.0"
env_logger = "0.11.8"
hashbrown = "0.16.1"
indexmap = "2.12.1"
lazy_static = "1.5.0"
log = "0.4.28"
pollster = "0.4.0"
rustc-hash = "2.1.1"
serde = "1.0"
smallvec = "1.15.1"
thiserror = "2.0.17"
uuid.version = "1.16.0"
uuid.features = ["v4"]
parking_lot = "0.12.5"

## Main package

[package]
name = "depot_tools"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
env_logger.workspace = true
parking_lot.workspace = true
depot_core.path = "core"
widget.path = "widget"

[dev-dependencies]
ratatui = "0.29.0"
