[package]
name = "widget"
version.workspace = true
edition.workspace = true

[dependencies]
bytemuck.workspace = true
env_logger.workspace = true
lazy_static.workspace = true
log.workspace = true
pollster.workspace = true
winit.workspace = true
glam = "0.30.4"
wgpu = "25.0.2"

[lib]
name = "widget"
crate-type = ["dylib"]
