[package]
name = "widget"
version.workspace = true
edition.workspace = true

[dependencies]
cosmic-text = "0.14.2"
fontconfig = "0.10.0"
global-hotkey = "0.7.0"
log.workspace = true
sdl3 = { version = "0.16.1", features = ["ttf"] }
smallvec.workspace = true
thiserror.workspace = true

[lib]
name = "widget"
